#!/usr/bin/env node

const { execSync } = require('child_process');

execSync(
    'BABEL_ENV=development ./node_modules/.bin/babel src --out-dir dist/cjs'
);

console.log('✓ CommonJS');

execSync(
    'BABEL_ENV=es ./node_modules/.bin/babel src --out-dir dist/es'
);

console.log('✓ ES');
